# Redis configuration file

# Lắng nghe mọi địa chỉ IP
bind 0.0.0.0

# Cổng mặc định
port 6379

# Giới hạn bộ nhớ 256MB
maxmemory 256mb
maxmemory-policy allkeys-lru

# Bật tính năng lưu trữ dữ liệu xuống đĩa
appendonly yes

# Mật khẩu truy cập
requirepass my_redis_password
