services:
  redis-limited:
    image: redis:alpine
    container_name: redis-limited
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 50M
        reservations:
          cpus: '0.10'
          memory: 20M
    ports:
      - "6380:6379"
