services:
  db:
    image: postgres:latest
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  adminer:
    image: adminer:latest
    container_name: adminer-ui
    restart: always
    ports:
      - "8083:8080"
    depends_on:
      - db
