services:
  db:
    image: mysql:8.0
    container_name: mysql-db-bai8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"

  app:
    build: .
    container_name: node-app-bai8
    ports:
      - "3000:3000"
    depends_on:
      - db
